version: "3"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=mi-clave-segura
      - NODE_ENV=production
      - N8N_HOST=n8n-tu-nombre.onrender.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - EXECUTIONS_MODE=queue
    ports:
      - "5678:5678"
    volumes:
      - .n8n:/home/node/.n8n
